# Generated by Django 6.0.2 on 2026-02-06 21:32

import django.core.validators
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(validators=[expenses.models.validate_not_future]),
        ),
    ]
